import { memo } from "react";
import bookLoaderWebp from "../assets/book-loader.webp";

// Animated WebP loader. Replaces the prior JS-driven Lottie animation with
// the browser's native image-decoder pipeline so the loop stays smooth even
// when the main thread is fully blocked by parser work (large EPUB/DOCX),
// React reconciliation, or any other synchronous JS. The WebP is decoded +
// scheduled by the browser independently of the JS event loop.
//
// Tradeoff: colors are baked into the WebP at export time. Per-theme
// recoloring (previously done by walking the Lottie JSON and remapping its
// 5 source colors via `recolorInPlace`) is no longer possible. `t` is still
// accepted by callers but unused inside; kept off the destructure as a
// no-op to avoid touching every call site.
//
// Source asset: src/assets/book-loader.webp — generated by downscaling the
// original 1500×1500 Lottie export to 300×300 lossless animated WebP via
// Pillow's Lanczos resampler. The Lottie JSON source is no longer in-repo;
// recover from git history (pre-WebP-swap commit) if a re-export is needed.
const BookLoader = memo(function BookLoader({ size = 220, style }) {
  return (
    <img
      src={bookLoaderWebp}
      role="status"
      aria-label="Loading"
      alt=""
      style={{ width: size, height: size, ...style }}
    />
  );
});

export default BookLoader;
